management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:h2:./.local-db/customers
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
cors:
  allowed-origins: ${ALLOWED_ORIGINS:'https://editor.swagger.io,*.huk-coburg.de'}
  allowed-credentials: ${ALLOWED_CREDENTIALS:true}
