GET {{endpoint}}/customers
Accept: application/json

> {%
 client.test('Customers read successfully', () => {
     client.assert(response.status === 200);
 });
%}

###

GET {{endpoint}}/customers
Accept: application/xml

> {%
    client.test('XML content type not available', () => {
        client.assert(response.status === 406);
    });
%}

###
PUT {{endpoint}}/customers/adad9102-08dd-4b0b-90fc-85207ac41e78
Content-Type: application/json

{
  "name": "Tom Tom",
  "birthdate": "2000-02-14",
  "state": "locked"
}

> {%
    client.test('Replaced successfully', () => {
        client.assert(response.status === 204);
    });
%}
